name: todo-app

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Get code
              uses: actions/checkout@v3  # This is used to fetch the code from the github repository and download it on the runner machine.
            
            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Docker build image
              uses: docker build -t my-web-app .

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        
            - name: Amazon ECR "Login" Action for GitHub Actions
              uses: aws-actions/amazon-ecr-login@v2
            

           # - name: Push docker image to ECR
            #docker push 969565240312.dkr.ecr.us-east-1.amazonaws.com/test:latest


           # - name : Deploy to EC2


