name: todo-app
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Get code
              uses: actions/checkout@v4  # This is used to fetch the code from the github repository and download it on the runner machine.
            
            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Docker build image
              uses: docker build -t my-web-app .

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1