name: todo-app

on:
    workflow_dispatch

#env:
   # AWS_REGION : "us-east-1"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Get code
              uses: actions/checkout@v3  # This is used to fetch the code from the github repository and download it on the runner machine.

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                aws-region: ${{ secrets.AWS_REGION}}
                role-to-assume: ${{ secrets.AWS_ROLE }}
                
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
        
            - name: Build, tag, and push docker image to Amazon ECR
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: myapp_image
                IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -t my-app -f backend/Dockerfile .
                  docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  #          - name: Build and tag docker image
   #           env:
   #             REGISTRY: ${{ steps.login-ecr-public.outputs.registry }} ## copy the ecr url output here
    #            REPOSITORY: myapp_image
   #             IMAGE_TAG: ${{ github.sha }}
    #          run: |
    #            docker build -t my-app -f backend/Dockerfile .
              




